// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Same files Next.js reads locally, `.env.local` first (the first file wins per key; a variable already set in the
// shell or CI always wins). `dotenv/config` alone read only `.env`, so `npm run db:migrate` missed `.env.local`.
config({ path: [".env.local", ".env"], quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only for diffing the migrations folder (CI's migrations-match-schema check, `prisma migrate dev`): an empty,
    // throwaway database Prisma may wipe. Never a real one.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
