-- Follow-up to rename-db-to-english.sql: constraint/index/sequence renames so the DB
-- catalog is byte-identical to what the @map-free schema generates (prisma db push = no-op).
-- GENERATED by scripts/generate-followup.mjs — do not hand-edit.

ALTER TABLE "GroupMember" RENAME CONSTRAINT "membro_grupo_pkey" TO "GroupMember_pkey";
ALTER TABLE "Category" RENAME CONSTRAINT "categoria_casa_pkey" TO "Category_pkey";
ALTER TABLE "Platform" RENAME CONSTRAINT "plataforma_pkey" TO "Platform_pkey";
ALTER TABLE "PaymentMethod" RENAME CONSTRAINT "forma_pagamento_casa_pkey" TO "PaymentMethod_pkey";
ALTER TABLE "ShoppingItem" RENAME CONSTRAINT "item_compra_pkey" TO "ShoppingItem_pkey";
ALTER TABLE "Settlement" RENAME CONSTRAINT "acerto_pkey" TO "Settlement_pkey";
ALTER TABLE "AuditLog" RENAME CONSTRAINT "registro_auditoria_pkey" TO "AuditLog_pkey";
ALTER TABLE "EntityRevision" RENAME CONSTRAINT "revisao_entidade_pkey" TO "EntityRevision_pkey";
ALTER TABLE "GroupMember" RENAME CONSTRAINT "membro_grupo_userId_fkey" TO "GroupMember_userId_fkey";
ALTER TABLE "GroupMember" RENAME CONSTRAINT "membro_grupo_groupId_fkey" TO "GroupMember_groupId_fkey";
ALTER TABLE "Category" RENAME CONSTRAINT "categoria_casa_grupo_id_fkey" TO "Category_groupId_fkey";
ALTER TABLE "Platform" RENAME CONSTRAINT "plataforma_grupo_id_fkey" TO "Platform_groupId_fkey";
ALTER TABLE "PaymentMethod" RENAME CONSTRAINT "forma_pagamento_casa_grupo_id_fkey" TO "PaymentMethod_groupId_fkey";
ALTER TABLE "ShoppingItem" RENAME CONSTRAINT "item_compra_groupId_fkey" TO "ShoppingItem_groupId_fkey";
ALTER TABLE "ShoppingItem" RENAME CONSTRAINT "item_compra_adicionado_por_fkey" TO "ShoppingItem_addedById_fkey";
ALTER TABLE "Settlement" RENAME CONSTRAINT "acerto_groupId_fkey" TO "Settlement_groupId_fkey";
ALTER TABLE "Settlement" RENAME CONSTRAINT "acerto_de_usuario_fkey" TO "Settlement_fromUserId_fkey";
ALTER TABLE "Settlement" RENAME CONSTRAINT "acerto_para_usuario_fkey" TO "Settlement_toUserId_fkey";
ALTER TABLE "Settlement" RENAME CONSTRAINT "acerto_criado_por_fkey" TO "Settlement_createdById_fkey";
ALTER TABLE "AuditLog" RENAME CONSTRAINT "registro_auditoria_groupId_fkey" TO "AuditLog_groupId_fkey";
ALTER TABLE "AuditLog" RENAME CONSTRAINT "registro_auditoria_autor_fkey" TO "AuditLog_actorId_fkey";

ALTER INDEX "User_usuario_key" RENAME TO "User_username_key";
ALTER INDEX "User_google_id_key" RENAME TO "User_googleId_key";
ALTER INDEX "Group_codigo_convite_key" RENAME TO "Group_joinCode_key";
ALTER INDEX "membro_grupo_groupId_idx" RENAME TO "GroupMember_groupId_idx";
ALTER INDEX "membro_grupo_userId_groupId_key" RENAME TO "GroupMember_userId_groupId_key";
ALTER INDEX "categoria_casa_publicId_key" RENAME TO "Category_publicId_key";
ALTER INDEX "categoria_casa_grupo_id_idx" RENAME TO "Category_groupId_idx";
ALTER INDEX "categoria_casa_grupo_id_nome_key" RENAME TO "Category_groupId_name_key";
ALTER INDEX "plataforma_publicId_key" RENAME TO "Platform_publicId_key";
ALTER INDEX "plataforma_grupo_id_idx" RENAME TO "Platform_groupId_idx";
ALTER INDEX "plataforma_grupo_id_nome_key" RENAME TO "Platform_groupId_name_key";
ALTER INDEX "forma_pagamento_casa_publicId_key" RENAME TO "PaymentMethod_publicId_key";
ALTER INDEX "forma_pagamento_casa_grupo_id_idx" RENAME TO "PaymentMethod_groupId_idx";
ALTER INDEX "forma_pagamento_casa_grupo_id_nome_key" RENAME TO "PaymentMethod_groupId_name_key";
ALTER INDEX "Expense_groupId_data_idx" RENAME TO "Expense_groupId_date_idx";
ALTER INDEX "item_compra_publicId_key" RENAME TO "ShoppingItem_publicId_key";
ALTER INDEX "item_compra_publicId_idx" RENAME TO "ShoppingItem_publicId_idx";
ALTER INDEX "item_compra_groupId_comprado_idx" RENAME TO "ShoppingItem_groupId_isPurchased_idx";
ALTER INDEX "acerto_publicId_key" RENAME TO "Settlement_publicId_key";
ALTER INDEX "acerto_publicId_idx" RENAME TO "Settlement_publicId_idx";
ALTER INDEX "acerto_groupId_data_idx" RENAME TO "Settlement_groupId_date_idx";
ALTER INDEX "registro_auditoria_groupId_createdAt_idx" RENAME TO "AuditLog_groupId_createdAt_idx";
ALTER INDEX "revisao_entidade_tipo_entidade_entidade_id_createdAt_idx" RENAME TO "EntityRevision_entityType_entityId_createdAt_idx";
ALTER INDEX "revisao_entidade_grupo_id_createdAt_idx" RENAME TO "EntityRevision_groupId_createdAt_idx";

ALTER SEQUENCE "acerto_id_seq" RENAME TO "Settlement_id_seq";
ALTER SEQUENCE "categoria_casa_id_seq" RENAME TO "Category_id_seq";
ALTER SEQUENCE "forma_pagamento_casa_id_seq" RENAME TO "PaymentMethod_id_seq";
ALTER SEQUENCE "item_compra_id_seq" RENAME TO "ShoppingItem_id_seq";
ALTER SEQUENCE "membro_grupo_id_seq" RENAME TO "GroupMember_id_seq";
ALTER SEQUENCE "plataforma_id_seq" RENAME TO "Platform_id_seq";
ALTER SEQUENCE "registro_auditoria_id_seq" RENAME TO "AuditLog_id_seq";
ALTER SEQUENCE "revisao_entidade_id_seq" RENAME TO "EntityRevision_id_seq";
